// --- IL NUOVO LINGUE.JS DEFINITIVO ---
window.traduzioni = {
    it: {
        torna_dashboard: "Torna alla Dashboard", torna_home: "Torna alla Home", caricamento_dati: "Sincronizzazione dati dal server in corso...",
        tab_login: "Login", tab_registrati: "Registrati", ph_nome: "Nome", ph_cognome: "Cognome", ph_email: "Email", ph_password: "Password", btn_accedi: "Accedi", btn_crea_account: "Crea Account",
        nav_mappa: "Mappa", nav_calendario: "Calendario", nav_segnala: "Segnala", nav_ingombranti: "Ingombranti", nav_profilo: "Il Mio Profilo", nav_guida: "Guida al Riciclo", nav_accedi: "Accedi", nav_esci: "Esci",
        mappa_esplora_titolo: "Esplora Trento", mappa_esplora_desc: "Clicca su un'area della mappa per vedere i giorni di raccolta della zona, o seleziona un'icona per i punti di raccolta speciali (Olio esausto, RAEE).", mappa_info_zona: "info zona di residenza", mappa_cal_attivo: "Calendario Porta a Porta attivo questa settimana", mappa_regole_esp: "Regole Esposizione Rifiuti:", mappa_attenzione_sacchi: "Attenzione: Esporre i sacchi o i mastelli sul suolo pubblico esclusivamente nei giorni e negli orari indicati.", mappa_punto_speciale: "punto di raccolta speciale", mappa_categoria: "Categoria:", mappa_dove_trova: "Dove si trova:", mappa_note_uso: "Note d'uso:", mappa_stato: "Stato:", msg_logout_success: "Logout effettuato correttamente.",
        profilo_caricamento: "Caricamento profilo...", profilo_utente_fallback: "Utente", profilo_ruolo: "Ruolo:", profilo_nome: "Nome", profilo_cognome: "Cognome", profilo_indirizzo: "Indirizzo Principale", profilo_ph_nome: "Inserisci il tuo nome", profilo_ph_cognome: "Inserisci il tuo cognome", profilo_ph_indirizzo: "Via / Piazza", profilo_pref_notifiche: "Preferenze Notifiche", profilo_pref_lingua: "Preferenze Lingua / Language", profilo_notif_app: "Notifiche App", profilo_notif_email: "Notifiche Email", profilo_btn_modifica: "Modifica Dati", profilo_btn_salva: "Salva Modifiche", profilo_btn_esci: "Esci",
        segnala_titolo: "Invia una Segnalazione", segnala_sottotitolo: "Aiutaci a mantenere Trento pulita. Segnala cestini pieni o rifiuti abbandonati.", segnala_tipo_prob: "Tipo di Problema", segnala_ph_categoria: "Seleziona una categoria...", segnala_opt_abbandono: "Rifiuti abbandonati sul suolo pubblico", segnala_opt_guasta: "Campana / Isola ecologica danneggiata", segnala_opt_altro: "Mancata raccolta o altro problema", segnala_via: "Via / Piazza di Trento", segnala_ph_via: "Esempio: Via Belenzani", segnala_desc: "Descrizione Dettagliata", segnala_ph_desc: "Descrivi il problema (es: vicino al civico 10...)", segnala_btn_invia: "INVIA SEGNALAZIONE", msg_invio_segnalazione: "Invio segnalazione in corso...", msg_indirizzo_segnalato: "Indirizzo Segnalato", msg_segnalazione_successo: "Segnalazione inviata con successo! Grazie per il tuo aiuto.", msg_errore_connessione: "Errore di connessione al server o sessione scaduta.",
        titolo_segnalazioni: "Gestione Segnalazioni", filtro_tutte: "Tutte le Segnalazioni", filtro_nuove: "Nuove (Aperte)", filtro_lavorazione: "In Lavorazione", filtro_risolte: "Archivio (Risolte)", nessuna_segnalazione: "Nessuna segnalazione trovata. Ottimo lavoro!", indirizzo_titolo: "Via/Indirizzo:", indirizzo_mancante: "Non specificata", btn_carico: "Prendi in Carico", btn_risolta: "Segna come Risolta",
        ingom_titolo: "Prenota Ritiro Ingombranti", ingom_sottotitolo: "Servizio di ritiro a domicilio per mobili e grandi elettrodomestici (Max 3 pezzi).", ingom_cosa_ritirare: "Cosa dobbiamo ritirare?", ingom_ph_pezzo: "Scegli il pezzo principale...", ingom_opt_mobili: "Mobili (Divano, Armadio, Tavolo)", ingom_opt_elettro: "Grandi Elettrodomestici (Frigo, Lavatrice)", ingom_opt_materassi: "Materassi o reti letto", ingom_opt_altro: "Altro (specificare nelle note)", ingom_data: "Data desiderata", ingom_fascia: "Fascia Oraria", ingom_ph_orario: "Scegli l'orario...", ingom_opt_mattina: "Mattina (08:00 - 12:00)", ingom_opt_pomeriggio: "Pomeriggio (13:00 - 17:00)", ingom_indirizzo: "Indirizzo di Ritiro (Trento)", ingom_ph_indirizzo: "Via e numero civico", ingom_btn_prenota: "PRENOTA RITIRO", msg_invio_corso: "Invio in corso...", msg_indirizzo_digitato: "Indirizzo digitato", msg_richiesta_successo: "Richiesta inviata con successo!", msg_errore_server: "Accesso negato o errore del server.",
        titolo_ingombranti: "Gestione Ingombranti", filtro_tutte_req: "Tutte le Richieste", filtro_attesa: "Da Accettare (In Attesa)", filtro_accettate: "Da Ritirare (Accettate)", filtro_completate: "Storico (Completate)", filtro_annullate: "Annullate", nessuna_richiesta: "Nessuna richiesta trovata per questa categoria.", data_ritiro: "Data Ritiro:", btn_accetta: "Accetta", btn_completa: "Segna Completata", btn_annulla: "Annulla",
        cal_titolo: "Il Tuo Calendario", cal_sottotitolo: "Seleziona la tua circoscrizione per consultare o stampare il calendario ufficiale della raccolta differenziata.", cal_label_quartiere: "Quartiere di Trento", cal_opt_caricamento: "Caricamento zone in corso...", cal_recupero_doc: "Recupero documento in corso...", cal_formato_pdf: "Formato PDF Stampabile", cal_btn_stampa: "Apri e Stampa"
    },
    en: {
        torna_dashboard: "Back to Dashboard", torna_home: "Back to Home", caricamento_dati: "Synchronizing data from server...",
        tab_login: "Login", tab_registrati: "Register", ph_nome: "Name", ph_cognome: "Surname", ph_email: "Email", ph_password: "Password", btn_accedi: "Sign In", btn_crea_account: "Create Account",
        nav_mappa: "Map", nav_calendario: "Calendar", nav_segnala: "Report", nav_ingombranti: "Bulky Waste", nav_profilo: "My Profile", nav_guida: "Recycling Guide", nav_accedi: "Sign In", nav_esci: "Logout",
        mappa_esplora_titolo: "Explore Trento", mappa_esplora_desc: "Click on an area of the map to see the collection days for the zone, or select an icon for special collection points.", mappa_info_zona: "residence zone info", mappa_cal_attivo: "Door-to-Door Calendar active this week", mappa_regole_esp: "Waste Exposure Rules:", mappa_attenzione_sacchi: "Attention: Place bags or bins on public land strictly on the designated days and times.", mappa_punto_speciale: "special collection point", mappa_categoria: "Category:", mappa_dove_trova: "Location:", mappa_note_uso: "Usage notes:", mappa_stato: "Status:", msg_logout_success: "Logout successfully completed.",
        profilo_caricamento: "Loading profile...", profilo_utente_fallback: "User", profilo_ruolo: "Role:", profilo_nome: "Name", profilo_cognome: "Surname", profilo_indirizzo: "Main Address", profilo_ph_nome: "Enter your name", profilo_ph_cognome: "Enter your surname", profilo_ph_indirizzo: "Street / Square", profilo_pref_notifiche: "Notification Preferences", profilo_pref_lingua: "Language Preferences", profilo_notif_app: "App Notifications", profilo_notif_email: "Email Notifications", profilo_btn_modifica: "Edit Data", profilo_btn_salva: "Save Changes", profilo_btn_esci: "Logout",
        segnala_titolo: "Submit a Report", segnala_sottotitolo: "Help us keep Trento clean. Report overflowing bins or abandoned waste.", segnala_tipo_prob: "Type of Problem", segnala_ph_categoria: "Select a category...", segnala_opt_abbandono: "Waste abandoned on public land", segnala_opt_guasta: "Damaged ecological island / bin", segnala_opt_altro: "Missed collection or other problem", segnala_via: "Street / Square in Trento", segnala_ph_via: "Example: Via Belenzani", segnala_desc: "Detailed Description", segnala_ph_desc: "Describe the problem (e.g., near building number 10...)", segnala_btn_invia: "SUBMIT REPORT", msg_invio_segnalazione: "Sending report...", msg_indirizzo_segnalato: "Reported Address", msg_segnalazione_successo: "Report sent successfully! Thank you for your help.", msg_errore_connessione: "Server connection error or session expired.",
        titolo_segnalazioni: "Reports Management", filtro_tutte: "All Reports", filtro_nuove: "New (Open)", filtro_lavorazione: "In Progress", filtro_risolte: "Archive (Resolved)", nessuna_segnalazione: "No reports found. Great job!", indirizzo_titolo: "Street/Address:", indirizzo_mancante: "Not specified", btn_carico: "Take Charge", btn_risolta: "Mark as Resolved",
        ingom_titolo: "Book Bulky Waste Collection", ingom_sottotitolo: "Home collection service for furniture and large appliances (Max 3 pieces).", ingom_cosa_ritirare: "What should we collect?", ingom_ph_pezzo: "Choose the main item...", ingom_opt_mobili: "Furniture (Sofa, Wardrobe, Table)", ingom_opt_elettro: "Large Appliances (Fridge, Washing Machine)", ingom_opt_materassi: "Mattresses or bed bases", ingom_opt_altro: "Other (specify in notes)", ingom_data: "Preferred Date", ingom_fascia: "Time Slot", ingom_ph_orario: "Choose the time...", ingom_opt_mattina: "Morning (08:00 - 12:00)", ingom_opt_pomeriggio: "Afternoon (13:00 - 17:00)", ingom_indirizzo: "Collection Address (Trento)", ingom_ph_indirizzo: "Street and house number", ingom_btn_prenota: "BOOK COLLECTION", msg_invio_corso: "Sending in progress...", msg_indirizzo_digitato: "Entered address", msg_richiesta_successo: "Request sent successfully!", msg_errore_server: "Access denied or server error.",
        titolo_ingombranti: "Bulky Waste Management", filtro_tutte_req: "All Requests", filtro_attesa: "To Accept (Pending)", filtro_accettate: "To Collect (Accepted)", filtro_completate: "History (Completed)", filtro_annullate: "Cancelled", nessuna_richiesta: "No requests found for this category.", data_ritiro: "Collection Date:", btn_accetta: "Accept", btn_completa: "Mark Completed", btn_annulla: "Cancel",
        cal_titolo: "Your Calendar", cal_sottotitolo: "Select your district to view or print the official waste collection calendar.", cal_label_quartiere: "Trento District", cal_opt_caricamento: "Loading zones...", cal_recupero_doc: "Retrieving document...", cal_formato_pdf: "Printable PDF Format", cal_btn_stampa: "Open and Print"
    }
};

window.i18n = {
    cambiaLingua(lang) {
        if (window.traduzioni[lang]) {
            localStorage.setItem('eco_lang', lang);
            window.location.reload(); // Il vero segreto: ricarica la pagina applicando tutto subito!
        }
    },
    t(chiave) {
        const lingua = localStorage.getItem('eco_lang') || 'it';
        return window.traduzioni[lingua][chiave] || chiave;
    }
};